Add AreaQuery param to getRenderedFeatures
felt/js-sdk pull request #5
Opened 2024-11-26 01:30 UTC by noisyneuron

This adds an optional `areaQuery` param to `getRenderedFeatures`

2024-11-26 08:05 UTC, tomhicks commented on docs/Layers/GetRenderedFeaturesConstraint.md
> +The ids of the layers to get rendered features for.
incorrect description of the parameter

2024-11-26 08:08 UTC, tomhicks commented on docs/Layers/GetRenderedFeaturesConstraint.md
> +> `optional` **areaQuery**: \{`type`: `"point"`;`latitude`: `number`;`longitude`: `number`; } | \{`type`: `"bbox"`;`boundary`: `FeltBoundarySchema`; }
I think we have a reusable latitude/longitude type which we could use, so it's more consistent with the other mmber of the union:
`{type: "thing", value: specificThing}`

2024-11-26 08:10 UTC, tomhicks commented on docs/Layers/GetRenderedFeaturesConstraint.md
> +The ids of the layers to get rendered features for.
I think it would be nice to mention something about the pixel radius around the point? I presume we do something like that in felt?

2024-11-26 08:18 UTC, tomhicks commented on src/modules/layers/types.ts
> +  }),
see what happens if you TSdoc these union members and properties. no idea what the doc generation will do, but it could be helpful for users to have it explained?

and I just realised that above, I've been commenting on the docs instead of the source 🙃

2024-11-26 08:19 UTC, tomhicks commented on src/modules/layers/types.ts
> +  areaQuery: AreaQuerySchema.optional(),
it might be worth trying inlining the schema here... not entirely sure what the doc-gen does etc., etc. but would be good to try to get the most unambiguous, explicit description of this that we can.

2024-11-26 08:22 UTC, tomhicks commented on src/modules/layers/types.ts
> +  areaQuery: AreaQuerySchema.optional(),
We should also update the docs for the Constraint itself, so that we make it clear that each constraint can be individually applied and combined. I think the name "constraint" plus their optional nature makes this pretty clear anyway, but I think being explicit will help.

And, it won't hurt to expand the top-level docs on the GetRenderedFeaturesConstraint page - I think having those descriptions nice and full makes the pages look nicer and more worthwhile!

2024-11-26 08:39 UTC, tomhicks commented on src/modules/layers/types.ts
> +  }),
Wondering whether we could make these just: `{coordinate: LatLng} | {bounds: FeltBoundary}` or even just `LatLng | FeltBoundary`?

At the very least, to be consistent with our other naming and shaping elsewhere, we should do:
```ts
{type: "coordinate", coordinate: LatLng} |
{type: "bounds", bounds: FeltBoundary}
```

But once you write that `{type: "thing", thing: Thing}` out it starts to make the skinny union of `LatLng | FeltBoundary` look more attractive!

Unsure about how skinny to make it - the skinnier we make it the more annoying it'll be to introduce things like LatLngTuple as [number, number] as we'll have to check the length of the array to disambiguate from a boundary, and stuff like that.

Maybe `{coordinate: LatLng}` provides a nice middle ground?

To finish the essay, I guess we need to optimise our input and return types for the SDK user:
- return types should be discriminated unions because it makes it easier for the recipient
- input types should be easy and unambiguous to write, even if it makes it slightly annoying for us to parse on the other side.

2024-11-26 08:40 UTC, tomhicks requested changes
I've added a bunch of feedback, mostly about documentation. The only thing that absolutely needs to be done is updating the description of the area query because currently it says it's the layer IDs.

The next most important thing (not necessarily to change but at least to consider) is to have a look at the input type for AreaQuery.

-- 

Sorry there are so many comments. So much of it is me thinking about consistency, future-proofing, considering how each piece of code ends up appearing to a user (e.g. hovers in VSCode, docs, etc.) and the different "entry points" into them.

2024-11-26 08:48 UTC, tomhicks commented on docs/Layers/GetRenderedFeaturesConstraint.md
> +The ids of the layers to get rendered features for.
Oh, I also think this needs to have a manual `{@link }` to the `AreaQuery` page because the docs are set to expand types for other reasons 🙃 .

If we are able to annotate each property maybe we can skip the AreaQuery page altogether somehow and have the only place it's documented be here.

2024-11-26 15:04 UTC, noisyneuron commented on docs/Layers/GetRenderedFeaturesConstraint.md
> +The ids of the layers to get rendered features for.
> I think it would be nice to mention something about the pixel radius around the point? I presume we do something like that in felt?

we don't -- if its a point we look just at that point 

> I would also mention the behaviour if this is not passed, which is to return features for the entire screen. then maaaaybe we should offer an explicit value for that: {type: "fullscreen"}

yea i was debating this -- explicit way to say fullscreen/viewport vs just omitting it.  i think omitting is fine? fine going either way if you have strong opinons

2024-11-27 15:25 UTC, tomhicks approved these changes
This looks nice!

2024-11-27 15:26 UTC, tomhicks requested changes
Just noticed the build is failing because we're linking `zod` into the client bundle:
```
✅ No disallowed strings found in client bundles.
```

2024-11-27 17:30 UTC, tomhicks approved these changes
I think it's good to go!

2024-11-27 17:55 UTC, merged